import { ResumeData, TemplateId, Theme, SectionType, Language } from './types';

export const INITIAL_RESUME_DATA: ResumeData = {
  personalInfo: {
    name: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
    profilePicture: null,
  },
  summary: '',
  sections: [
    {
      id: 'experience',
      title: 'Experience',
      isVisible: true,
      items: [
        {
          id: 'exp1',
          company: '',
          role: '',
          startDate: '',
          endDate: '',
          description: '',
        },
      ],
    },
    {
      id: 'education',
      title: 'Education',
      isVisible: true,
      items: [
        {
          id: 'edu1',
          institution: '',
          degree: '',
          startDate: '',
          endDate: '',
          details: '',
        },
      ],
    },
    {
        id: 'skills',
        title: 'Skills',
        isVisible: true,
        items: [
            { id: 'skill1', name: '', level: 'Intermediate' },
        ]
    },
    {
        id: 'projects',
        title: 'Projects',
        isVisible: true,
        items: [
            { id: 'proj1', name: '', description: '', link: '' },
        ]
    },
    {
        id: 'languages',
        title: 'Languages',
        isVisible: true,
        items: [
            { id: 'lang1', name: '', proficiency: 'Intermediate' },
        ]
    },
    {
        id: 'interests',
        title: 'Interests',
        isVisible: true,
        items: [
            { id: 'int1', name: '' },
        ]
    }
  ],
};

export const TEMPLATES: { id: TemplateId; nameKey: string }[] = [
  { id: 'classic', nameKey: 'template_classic' },
  { id: 'ats-minimal', nameKey: 'template_ats_minimal' },
  { id: 'modern-two-column', nameKey: 'template_modern_two_column' },
  { id: 'creative-bold', nameKey: 'template_creative_bold' },
  { id: 'executive-summary', nameKey: 'template_executive_summary' },
  { id: 'tech-innovator', nameKey: 'template_tech_innovator' },
  { id: 'academic-cv', nameKey: 'template_academic_cv' },
  { id: 'fresher-skills-first', nameKey: 'template_fresher_skills_first' },
  { id: 'info-sidebar', nameKey: 'template_info_sidebar' },
  { id: 'corporate-header', nameKey: 'template_corporate_header' },
];

export const THEMES: Theme[] = [
  { name: 'Blue', primaryColor: '#3b82f6', secondaryColor: '#93c5fd' },
  { name: 'Teal', primaryColor: '#14b8a6', secondaryColor: '#99f6e4' },
  { name: 'Emerald', primaryColor: '#10b981', secondaryColor: '#a7f3d0' },
  { name: 'Violet', primaryColor: '#8b5cf6', secondaryColor: '#ddd6fe' },
  { name: 'Rose', primaryColor: '#f43f5e', secondaryColor: '#fecdd3' },
  { name: 'Orange', primaryColor: '#f97316', secondaryColor: '#fed7aa' },
  { name: 'Sky', primaryColor: '#0ea5e9', secondaryColor: '#bae6fd' },
  { name: 'Gray', primaryColor: '#374151', secondaryColor: '#d1d5db' },
];

export const SECTION_CONFIG: Record<SectionType, { id: SectionType, titleKey: string, factory: () => any }> = {
    experience: { id: 'experience', titleKey: 'section_title_experience', factory: () => ({ id: crypto.randomUUID(), company: '', role: '', startDate: '', endDate: '', description: '' }) },
    education: { id: 'education', titleKey: 'section_title_education', factory: () => ({ id: crypto.randomUUID(), institution: '', degree: '', startDate: '', endDate: '', details: '' }) },
    skills: { id: 'skills', titleKey: 'section_title_skills', factory: () => ({ id: crypto.randomUUID(), name: '', level: 'Intermediate' }) },
    projects: { id: 'projects', titleKey: 'section_title_projects', factory: () => ({ id: crypto.randomUUID(), name: '', description: '', link: '' }) },
    certifications: { id: 'certifications', titleKey: 'section_title_certifications', factory: () => ({ id: crypto.randomUUID(), name: '', issuer: '', date: '' }) },
    languages: { id: 'languages', titleKey: 'section_title_languages', factory: () => ({ id: crypto.randomUUID(), name: '', proficiency: 'Intermediate' }) },
    interests: { id: 'interests', titleKey: 'section_title_interests', factory: () => ({ id: crypto.randomUUID(), name: '' }) },
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    "header_resume": "Resume",
    "header_cv": "CV",
    "header_cover_letter": "Cover Letter",
    "header_career_advice": "Career Advice",
    "header_about": "About",
    "home_title_1": "Make a great resume.",
    "home_title_2": "Simply.",
    "home_subtitle": "Create a powerful resume and cover letter in minutes. Make recruiters want to hire you. Get the job you've been dreaming of.",
    "home_cta": "CREATE YOUR RESUME",
    "form_personal_info_title": "Personal Information",
    "form_full_name_label": "Full Name",
    "form_job_title_label": "Job Title",
    "form_email_label": "Email",
    "form_phone_label": "Phone",
    "form_location_label": "Location",
    "form_website_label": "Website/Portfolio",
    "form_linkedin_label": "LinkedIn Profile",
    "form_github_label": "GitHub Profile",
    "form_profile_picture_label": "Profile Picture",
    "form_summary_title": "Summary",
    "form_summary_label": "Professional Summary",
    "form_summary_placeholder": "Write a brief summary about your professional background and skills.",
    "form_add_section_button": "Add Section",
    "form_preview_resume_button": "Preview Resume",
    "section_title_experience": "Experience",
    "section_title_education": "Education",
    "section_title_skills": "Skills",
    "section_title_projects": "Projects",
    "section_title_certifications": "Certifications",
    "section_title_languages": "Languages",
    "section_title_interests": "Interests",
    "toolbar_templates": "Templates",
    "toolbar_font": "Font",
    "toolbar_theme": "Theme",
    "download_button": "Download",
    "generating_button": "Generating...",
    "download_pdf": "Export as PDF",
    "download_docx": "Export as DOCX",
    "footer_home": "Home",
    "footer_about": "About",
    "footer_github": "GitHub",
    "footer_tagline": "Craft your professional story.",
    "footer_copyright": "© {year} ResumeLab. Created by Shivam Kumar. All rights reserved.",
    "about_title": "About ResumeLab",
    "about_subtitle": "An intuitive and powerful resume builder designed for job seekers who want polished, ATS-friendly resumes in minutes.",
    "about_developer_name": "Shivam Kumar",
    "about_developer_title": "Developer",
    "about_view_github": "View on GitHub",
    "about_features_title": "Key Features",
    "about_feature_1": "Professional Templates: Choose from a collection of modern, ATS-friendly resume templates.",
    "about_feature_2": "Easy Customization: Effortlessly change themes, fonts, and section layouts to match your personal brand.",
    "about_feature_3": "Dynamic Sections: Add, remove, and reorder sections with drag-and-drop.",
    "about_feature_4": "Instant Preview: See your resume update in real-time as you type.",
    "about_feature_5": "PDF & DOCX Export: Download high-quality resumes ready for any job application.",
    "template_classic": "Classic Chronological",
    "template_ats_minimal": "ATS Minimal",
    "template_modern_two_column": "Modern Two-Column",
    "template_creative_bold": "Creative Bold",
    "template_executive_summary": "Executive Summary",
    "template_tech_innovator": "Tech Innovator",
    "template_academic_cv": "Academic CV",
    "template_fresher_skills_first": "Fresher (Skills First)",
    "template_info_sidebar": "Infographic Sidebar",
    "template_corporate_header": "Corporate Header",
  },
  es: {
    "header_resume": "Currículum",
    "header_cv": "CV",
    "header_cover_letter": "Carta de Presentación",
    "header_career_advice": "Consejo Profesional",
    "header_about": "Sobre nosotros",
    "home_title_1": "Crea un currículum genial.",
    "home_title_2": "Simplemente.",
    "home_subtitle": "Crea un currículum y una carta de presentación impactantes en minutos. Haz que los reclutadores quieran contratarte. Consigue el trabajo de tus sueños.",
    "home_cta": "CREA TU CURRÍCULUM",
    "form_personal_info_title": "Información Personal",
    "form_full_name_label": "Nombre Completo",
    "form_job_title_label": "Puesto de Trabajo",
    "form_email_label": "Correo Electrónico",
    "form_phone_label": "Teléfono",
    "form_location_label": "Ubicación",
    "form_website_label": "Sitio Web/Portafolio",
    "form_linkedin_label": "Perfil de LinkedIn",
    "form_github_label": "Perfil de GitHub",
    "form_profile_picture_label": "Foto de Perfil",
    "form_summary_title": "Resumen",
    "form_summary_label": "Resumen Profesional",
    "form_summary_placeholder": "Escribe un breve resumen sobre tu experiencia profesional y tus habilidades.",
    "form_add_section_button": "Añadir Sección",
    "form_preview_resume_button": "Vista Previa del Currículum",
    "section_title_experience": "Experiencia",
    "section_title_education": "Educación",
    "section_title_skills": "Habilidades",
    "section_title_projects": "Proyectos",
    "section_title_certifications": "Certificaciones",
    "section_title_languages": "Idiomas",
    "section_title_interests": "Intereses",
    "toolbar_templates": "Plantillas",
    "toolbar_font": "Fuente",
    "toolbar_theme": "Tema",
    "download_button": "Descargar",
    "generating_button": "Generando...",
    "download_pdf": "Exportar como PDF",
    "download_docx": "Exportar como DOCX",
    "footer_home": "Inicio",
    "footer_about": "Sobre nosotros",
    "footer_github": "GitHub",
    "footer_tagline": "Elabora tu historia profesional.",
    "footer_copyright": "© {year} ResumeLab. Creado por Shivam Kumar. Todos los derechos reservados.",
    "about_title": "Sobre ResumeLab",
    "about_subtitle": "Un creador de currículums intuitivo y potente diseñado para buscadores de empleo que desean currículums pulidos y compatibles con ATS en minutos.",
    "about_developer_name": "Shivam Kumar",
    "about_developer_title": "Desarrollador",
    "about_view_github": "Ver en GitHub",
    "about_features_title": "Características Clave",
    "about_feature_1": "Plantillas Profesionales: Elige entre una colección de plantillas de currículum modernas y compatibles con ATS.",
    "about_feature_2": "Fácil Personalización: Cambia sin esfuerzo temas, fuentes y diseños de sección para que coincidan con tu marca personal.",
    "about_feature_3": "Secciones Dinámicas: Añade, elimina y reordena secciones con arrastrar y soltar.",
    "about_feature_4": "Vista Previa Instantánea: Ve cómo se actualiza tu currículum en tiempo real mientras escribes.",
    "about_feature_5": "Exportación a PDF y DOCX: Descarga currículums de alta calidad listos para cualquier solicitud de empleo.",
    "template_classic": "Clásico Cronológico",
    "template_ats_minimal": "ATS Mínimo",
    "template_modern_two_column": "Moderno de Dos Columnas",
    "template_creative_bold": "Creativo Audaz",
    "template_executive_summary": "Resumen Ejecutivo",
    "template_tech_innovator": "Innovador Tecnológico",
    "template_academic_cv": "CV Académico",
    "template_fresher_skills_first": "Recién Graduado (Habilidades Primero)",
    "template_info_sidebar": "Barra Lateral Infográfica",
    "template_corporate_header": "Encabezado Corporativo",
  },
  fr: {
    "header_resume": "CV",
    "header_cv": "CV Détaillé",
    "header_cover_letter": "Lettre de Motivation",
    "header_career_advice": "Conseils Carrière",
    "header_about": "À propos",
    "home_title_1": "Créez un CV remarquable.",
    "home_title_2": "Simplement.",
    "home_subtitle": "Créez un CV et une lettre de motivation percutants en quelques minutes. Donnez aux recruteurs l'envie de vous embaucher. Décrochez le job de vos rêves.",
    "home_cta": "CRÉER VOTRE CV",
    "form_personal_info_title": "Informations Personnelles",
    "form_full_name_label": "Nom Complet",
    "form_job_title_label": "Titre du Poste",
    "form_email_label": "E-mail",
    "form_phone_label": "Téléphone",
    "form_location_label": "Lieu",
    "form_website_label": "Site Web/Portfolio",
    "form_linkedin_label": "Profil LinkedIn",
    "form_github_label": "Profil GitHub",
    "form_profile_picture_label": "Photo de Profil",
    "form_summary_title": "Résumé",
    "form_summary_label": "Résumé Professionnel",
    "form_summary_placeholder": "Rédigez un bref résumé de votre parcours professionnel et de vos compétences.",
    "form_add_section_button": "Ajouter une Section",
    "form_preview_resume_button": "Aperçu du CV",
    "section_title_experience": "Expérience",
    "section_title_education": "Formation",
    "section_title_skills": "Compétences",
    "section_title_projects": "Projets",
    "section_title_certifications": "Certifications",
    "section_title_languages": "Langues",
    "section_title_interests": "Centres d'intérêt",
    "toolbar_templates": "Modèles",
    "toolbar_font": "Police",
    "toolbar_theme": "Thème",
    "download_button": "Télécharger",
    "generating_button": "Génération...",
    "download_pdf": "Exporter en PDF",
    "download_docx": "Exporter en DOCX",
    "footer_home": "Accueil",
    "footer_about": "À propos",
    "footer_github": "GitHub",
    "footer_tagline": "Racontez votre histoire professionnelle.",
    "footer_copyright": "© {year} ResumeLab. Créé par Shivam Kumar. Tous droits réservés.",
    "about_title": "À propos de ResumeLab",
    "about_subtitle": "Un créateur de CV intuitif et puissant conçu pour les demandeurs d'emploi qui veulent des CV soignés et compatibles ATS en quelques minutes.",
    "about_developer_name": "Shivam Kumar",
    "about_developer_title": "Développeur",
    "about_view_github": "Voir sur GitHub",
    "about_features_title": "Fonctionnalités Clés",
    "about_feature_1": "Modèles Professionnels : Choisissez parmi une collection de modèles de CV modernes et compatibles ATS.",
    "about_feature_2": "Personnalisation Facile : Changez sans effort les thèmes, les polices et la disposition des sections pour correspondre à votre marque personnelle.",
    "about_feature_3": "Sections Dynamiques : Ajoutez, supprimez et réorganisez les sections par glisser-déposer.",
    "about_feature_4": "Aperçu Instantané : Voyez votre CV se mettre à jour en temps réel pendant que vous écrivez.",
    "about_feature_5": "Exportation PDF & DOCX : Téléchargez des CV de haute qualité prêts pour toute candidature.",
    "template_classic": "Chronologique Classique",
    "template_ats_minimal": "ATS Minimaliste",
    "template_modern_two_column": "Moderne à Deux Colonnes",
    "template_creative_bold": "Créatif Audacieux",
    "template_executive_summary": "Résumé Exécutif",
    "template_tech_innovator": "Innovateur Tech",
    "template_academic_cv": "CV Académique",
    "template_fresher_skills_first": "Débutant (Compétences d'abord)",
    "template_info_sidebar": "Barre Latérale Infographique",
    "template_corporate_header": "En-tête d'Entreprise",
  },
  de: {
    "header_resume": "Lebenslauf",
    "header_cv": "CV",
    "header_cover_letter": "Anschreiben",
    "header_career_advice": "Karriereratgeber",
    "header_about": "Über uns",
    "home_title_1": "Erstellen Sie einen großartigen Lebenslauf.",
    "home_title_2": "Einfach.",
    "home_subtitle": "Erstellen Sie in wenigen Minuten einen aussagekräftigen Lebenslauf und ein Anschreiben. Wecken Sie das Interesse von Personalvermittlern. Holen Sie sich den Job, von dem Sie geträumt haben.",
    "home_cta": "LEBENSLAUF ERSTELLEN",
    "form_personal_info_title": "Persönliche Informationen",
    "form_full_name_label": "Vollständiger Name",
    "form_job_title_label": "Berufsbezeichnung",
    "form_email_label": "E-Mail",
    "form_phone_label": "Telefon",
    "form_location_label": "Standort",
    "form_website_label": "Webseite/Portfolio",
    "form_linkedin_label": "LinkedIn-Profil",
    "form_github_label": "GitHub-Profil",
    "form_profile_picture_label": "Profilbild",
    "form_summary_title": "Zusammenfassung",
    "form_summary_label": "Berufliches Profil",
    "form_summary_placeholder": "Schreiben Sie eine kurze Zusammenfassung über Ihren beruflichen Hintergrund und Ihre Fähigkeiten.",
    "form_add_section_button": "Abschnitt hinzufügen",
    "form_preview_resume_button": "Vorschau Lebenslauf",
    "section_title_experience": "Berufserfahrung",
    "section_title_education": "Ausbildung",
    "section_title_skills": "Fähigkeiten",
    "section_title_projects": "Projekte",
    "section_title_certifications": "Zertifizierungen",
    "section_title_languages": "Sprachen",
    "section_title_interests": "Interessen",
    "toolbar_templates": "Vorlagen",
    "toolbar_font": "Schriftart",
    "toolbar_theme": "Thema",
    "download_button": "Herunterladen",
    "generating_button": "Wird generiert...",
    "download_pdf": "Als PDF exportieren",
    "download_docx": "Als DOCX exportieren",
    "footer_home": "Startseite",
    "footer_about": "Über uns",
    "footer_github": "GitHub",
    "footer_tagline": "Gestalten Sie Ihre berufliche Geschichte.",
    "footer_copyright": "© {year} ResumeLab. Erstellt von Shivam Kumar. Alle Rechte vorbehalten.",
    "about_title": "Über ResumeLab",
    "about_subtitle": "Ein intuitiver und leistungsstarker Lebenslauf-Builder für Arbeitssuchende, die in wenigen Minuten ausgefeilte, ATS-freundliche Lebensläufe erstellen möchten.",
    "about_developer_name": "Shivam Kumar",
    "about_developer_title": "Entwickler",
    "about_view_github": "Auf GitHub ansehen",
    "about_features_title": "Hauptmerkmale",
    "about_feature_1": "Professionelle Vorlagen: Wählen Sie aus einer Sammlung moderner, ATS-freundlicher Lebenslaufvorlagen.",
    "about_feature_2": "Einfache Anpassung: Ändern Sie mühelos Themen, Schriftarten und Abschnittslayouts, um sie an Ihre persönliche Marke anzupassen.",
    "about_feature_3": "Dynamische Abschnitte: Fügen Sie Abschnitte per Drag-and-Drop hinzu, entfernen und neu anordnen.",
    "about_feature_4": "Sofortige Vorschau: Sehen Sie, wie sich Ihr Lebenslauf in Echtzeit aktualisiert, während Sie tippen.",
    "about_feature_5": "PDF- & DOCX-Export: Laden Sie hochwertige Lebensläufe herunter, die für jede Bewerbung bereit sind.",
    "template_classic": "Klassisch Chronologisch",
    "template_ats_minimal": "ATS Minimal",
    "template_modern_two_column": "Modern Zweispaltig",
    "template_creative_bold": "Kreativ Fett",
    "template_executive_summary": "Zusammenfassung für Führungskräfte",
    "template_tech_innovator": "Tech-Innovator",
    "template_academic_cv": "Akademischer CV",
    "template_fresher_skills_first": "Berufseinsteiger (Fähigkeiten zuerst)",
    "template_info_sidebar": "Infografik-Seitenleiste",
    "template_corporate_header": "Unternehmenskopfzeile",
  },
  hi: {
    "header_resume": "बायोडाटा",
    "header_cv": "सीवी",
    "header_cover_letter": "कवर लेटर",
    "header_career_advice": "करियर सलाह",
    "header_about": "हमारे बारे में",
    "home_title_1": "एक बेहतरीन बायोडाटा बनाएं।",
    "home_title_2": "सरलता से।",
    "home_subtitle": "मिनटों में एक शक्तिशाली बायोडाटा और कवर लेटर बनाएं। नियोक्ताओं को आपको काम पर रखने के लिए प्रेरित करें। अपने सपनों की नौकरी पाएं।",
    "home_cta": "अपना बायोडाटा बनाएं",
    "form_personal_info_title": "व्यक्तिगत जानकारी",
    "form_full_name_label": "पूरा नाम",
    "form_job_title_label": "पद का शीर्षक",
    "form_email_label": "ईमेल",
    "form_phone_label": "फ़ोन",
    "form_location_label": "स्थान",
    "form_website_label": "वेबसाइट/पोर्टफोलियो",
    "form_linkedin_label": "लिंक्डइन प्रोफ़ाइल",
    "form_github_label": "गिटहब प्रोफ़ाइल",
    "form_profile_picture_label": "प्रोफ़ाइल चित्र",
    "form_summary_title": "सारांश",
    "form_summary_label": "पेशेवर सारांश",
    "form_summary_placeholder": "अपनी पेशेवर पृष्ठभूमि और कौशल के बारे में एक संक्षिप्त सारांश लिखें।",
    "form_add_section_button": "अनुभाग जोड़ें",
    "form_preview_resume_button": "बायोडाटा का पूर्वावलोकन करें",
    "section_title_experience": "अनुभव",
    "section_title_education": "शिक्षा",
    "section_title_skills": "कौशल",
    "section_title_projects": "परियोजनाएं",
    "section_title_certifications": "प्रमाणपत्र",
    "section_title_languages": "भाषाएँ",
    "section_title_interests": "रुचियाँ",
    "toolbar_templates": "टेम्पलेट्स",
    "toolbar_font": "फ़ॉन्ट",
    "toolbar_theme": "थीम",
    "download_button": "डाउनलोड करें",
    "generating_button": "उत्पन्न हो रहा है...",
    "download_pdf": "पीडीएफ के रूप में निर्यात करें",
    "download_docx": "डीओसीएक्स के रूप में निर्यात करें",
    "footer_home": "होम",
    "footer_about": "हमारे बारे में",
    "footer_github": "गिटहब",
    "footer_tagline": "अपनी पेशेवर कहानी गढ़ें।",
    "footer_copyright": "© {year} ResumeLab. शिवम कुमार द्वारा बनाया गया। सर्वाधिकार सुरक्षित।",
    "about_title": "ResumeLab के बारे में",
    "about_subtitle": "नौकरी चाहने वालों के लिए बनाया गया एक सहज और शक्तिशाली बायोडाटा निर्माता जो मिनटों में पॉलिश, एटीएस-अनुकूल बायोडाटा चाहते हैं।",
    "about_developer_name": "शिवम कुमार",
    "about_developer_title": "डेवलपर",
    "about_view_github": "गिटहब पर देखें",
    "about_features_title": "मुख्य विशेषताएं",
    "about_feature_1": "पेशेवर टेम्पलेट्स: आधुनिक, एटीएस-अनुकूल बायोडाटा टेम्पलेट्स के संग्रह में से चुनें।",
    "about_feature_2": "आसान अनुकूलन: अपने व्यक्तिगत ब्रांड से मेल खाने के लिए थीम, फ़ॉन्ट और अनुभाग लेआउट को सहजता से बदलें।",
    "about_feature_3": "गतिशील अनुभाग: ड्रैग-एंड-ड्रॉप के साथ अनुभाग जोड़ें, हटाएं और पुनः व्यवस्थित करें।",
    "about_feature_4": "त्वरित पूर्वावलोकन: टाइप करते समय अपने बायोडाटा को वास्तविक समय में अपडेट होते देखें।",
    "about_feature_5": "पीडीएफ और डीओसीएक्स निर्यात: किसी भी नौकरी के आवेदन के लिए तैयार उच्च-गुणवत्ता वाले बायोडाटा डाउनलोड करें।",
    "template_classic": "क्लासिक कालानुक्रमिक",
    "template_ats_minimal": "एटीएस मिनिमल",
    "template_modern_two_column": "आधुनिक दो-कॉलम",
    "template_creative_bold": "क्रिएटिव बोल्ड",
    "template_executive_summary": "कार्यकारी सारांश",
    "template_tech_innovator": "टेक इनोवेटर",
    "template_academic_cv": "अकादमिक सीवी",
    "template_fresher_skills_first": "फ्रेशर (कौशल पहले)",
    "template_info_sidebar": "इन्फोग्राफिक साइडबार",
    "template_corporate_header": "कॉर्पोरेट हेडर",
  }
};